# Generated by Django 3.0.6 on 2020-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='option',
            field=models.CharField(default='cod', max_length=100),
        ),
    ]
