# Generated by Django 3.0.6 on 2020-06-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='option',
            field=models.CharField(max_length=100),
        ),
    ]
