# Generated by Django 3.0.6 on 2020-06-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200217_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated',
        ),
    ]
