# Generated by Django 3.0.6 on 2020-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200606_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='red', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default='small', max_length=200),
            preserve_default=False,
        ),
    ]
