# Generated by Django 3.0.6 on 2020-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200607_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(to='items.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(to='items.Colour'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(to='items.Size'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ManyToManyField(blank=True, null=True, to='items.Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.ManyToManyField(to='items.Label'),
        ),
    ]
