# Generated by Django 3.0.6 on 2020-06-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20200607_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='categories',
            field=models.ManyToManyField(to='items.Category'),
        ),
    ]
