# Generated by Django 3.0.6 on 2020-06-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20200607_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accessory',
            field=models.BooleanField(default=False),
        ),
    ]
