# Generated by Django 3.0.6 on 2020-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200607_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
