# Generated by Django 3.0.6 on 2020-06-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
